CREATE TABLE AUTHORITY (
   ID  BIGSERIAL NOT NULL,
   NAME VARCHAR(255),
   PRIMARY KEY (ID),
   UNIQUE (NAME)
);


CREATE TABLE USER_ACCOUNT(
   ID  BIGSERIAL NOT NULL,
   ACCOUNT_ID VARCHAR(255) NOT NULL,
   ACCOUNT_EXPIRED BOOLEAN,
   ACCOUNT_LOCKED BOOLEAN,
   CREDENTIALS_EXPIRED BOOLEAN,
   ENABLED BOOLEAN,
   PASSWORD VARCHAR(255) NOT NULL,
   USERNAME VARCHAR(255) NOT NULL,
   EMAIL VARCHAR(255) NOT NULL,
   created_date date NULL,
   last_updated_date date NULL,
   last_password_reset_date date NULL,
   OPERATOR VARCHAR(255),
   PRIMARY KEY (ID),
   UNIQUE (USERNAME,ACCOUNT_ID,EMAIL)
);

CREATE TABLE CUSTOMER_ACCOUNT(
   ID  BIGSERIAL NOT NULL,
   ACCOUNT_ID VARCHAR(255) NOT NULL,
   ACCOUNT_EXPIRED BOOLEAN,
   ACCOUNT_LOCKED BOOLEAN,
   CREDENTIALS_EXPIRED BOOLEAN,
   ENABLED BOOLEAN,
   PASSWORD VARCHAR(255) NOT NULL,
   USERNAME VARCHAR(255) NOT NULL,
   EMAIL VARCHAR(255) NOT NULL,
   created_date date NULL,
   last_updated_date date NULL,
   last_password_reset_date date NULL,
   OPERATOR VARCHAR(255),
   PRIMARY KEY (ID),
   UNIQUE (USERNAME,ACCOUNT_ID,EMAIL)
);


CREATE TABLE ACCOUNT_AUTHORITIES (
   ACCOUNT_ID INT8 NOT NULL,
   AUTHORITY_ID INT8 NOT NULL,
   PRIMARY KEY (ACCOUNT_ID, AUTHORITY_ID),

   CONSTRAINT fk_account
      FOREIGN KEY(ACCOUNT_ID)
	  REFERENCES USER_ACCOUNT(ID)
	  ON DELETE CASCADE,

   CONSTRAINT fk_authority
      FOREIGN KEY(AUTHORITY_ID)
	  REFERENCES AUTHORITY(ID)
	  ON DELETE CASCADE
);

CREATE TABLE CUSTOMER_ACCOUNT_AUTHORITIES (
   ACCOUNT_ID INT8 NOT NULL,
   AUTHORITY_ID INT8 NOT NULL,
   PRIMARY KEY (ACCOUNT_ID, AUTHORITY_ID),

   CONSTRAINT fk_account_2
      FOREIGN KEY(ACCOUNT_ID)
	  REFERENCES CUSTOMER_ACCOUNT(ID)
	  ON DELETE CASCADE,

   CONSTRAINT fk_authority_2
      FOREIGN KEY(AUTHORITY_ID)
	  REFERENCES AUTHORITY(ID)
	  ON DELETE CASCADE
);