INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'ADMIN');
INSERT INTO AUTHORITY(ID, NAME) VALUES (2, 'SUPERVISOR');
INSERT INTO AUTHORITY(ID, NAME) VALUES (3, 'COMMERCIAL');
INSERT INTO AUTHORITY(ID, NAME) VALUES (4, 'CUSTOMER');