INSERT INTO USER_ACCOUNT(ID, ACCOUNT_ID, USERNAME,  EMAIL, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED, OPERATOR)
  VALUES (1, '92d9b287-9eed-4a5c-a4ff-03ebd7f624aa', 'admin', 'admin@test.fr', /*admin1234*/'$2a$08$qvrzQZ7jJ7oy2p/msL4M0.l83Cd0jNsX6AJUitbgRXGzge4j035ha', FALSE, FALSE, FALSE, TRUE,'admin');

INSERT INTO USER_ACCOUNT(ID, ACCOUNT_ID,  USERNAME,  EMAIL,  PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED, OPERATOR)
  VALUES (2,'3f1af344-221a-4008-b793-28469bb6d9ce', 'superviseur', 'superviseur@gmail.com',  /*superviseur1234*/'$2a$08$pC1LHqe.F0WQFpPfVSvmCOcmMAaQvUDbTran/aALpLQjJTRQTnXZy', FALSE, FALSE, FALSE, TRUE, 'superviseur');

INSERT INTO USER_ACCOUNT(ID, ACCOUNT_ID,  USERNAME,  EMAIL,  PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED, OPERATOR)
  VALUES (3,'042fb7c3-dc3e-444d-aff2-92dd47d59691', 'commercial', 'commercial@gmail.com', /*commercial1234*/'$2a$08$gBb4N8C.3zZgBePp6R1exewR3wDzaHT.6X5y5jm/BZAXDCC3M2SP2', FALSE, FALSE, FALSE, TRUE, 'commercial');

INSERT INTO CUSTOMER_ACCOUNT(ID, ACCOUNT_ID,  USERNAME, EMAIL,  PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED, OPERATOR)
  VALUES (4,'52723a2f-6989-405c-abe6-5f9848bc359b', 'client', 'client.sofie@gmail.com',  /*client1234*/'$2a$08$vbHsbLY8XFWKiBf/HWqKc.t4b08ts63UdWJNc/UNUcOJDvzBl66F.', FALSE, FALSE, FALSE, TRUE,'client');

INSERT INTO ACCOUNT_AUTHORITIES(ACCOUNT_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO ACCOUNT_AUTHORITIES(ACCOUNT_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO ACCOUNT_AUTHORITIES(ACCOUNT_ID, AUTHORITY_ID) VALUES (1, 3);
INSERT INTO ACCOUNT_AUTHORITIES(ACCOUNT_ID, AUTHORITY_ID) VALUES (1, 4);
INSERT INTO ACCOUNT_AUTHORITIES(ACCOUNT_ID, AUTHORITY_ID) VALUES (2, 2);
INSERT INTO ACCOUNT_AUTHORITIES(ACCOUNT_ID, AUTHORITY_ID) VALUES (3, 3);
INSERT INTO CUSTOMER_ACCOUNT_AUTHORITIES(ACCOUNT_ID, AUTHORITY_ID) VALUES (4, 4);